server:
  port: 8888
spring:
  profiles:
    active: dev
---
server:
  port: 8888
spring:
  profiles: dev
  datasource:
    database: focus
    host: 127.0.0.1
    port: 3306
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&failOverReadOnly=false
    username: root
    password: 123321abc
  jpa:
    show-sql: true
security:
  token:
    header: X-Auth-Token
    secret: ca$hc0w1!
socketio:
  port: 8091
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring.boot.admin.client.url: http://testh5.com.cn:28226


spring.servlet.multipart.max-file-size: 3MB
spring.servlet.multipart.max-request-size: 5MB